### PR TITLE
deps: make typescript a dev dep, bump other deps

### PR DESCRIPTION
**Pull request by SuperchupuDev**
currently, a copy of typescript gets installed for everyone that installs this package, this PR changes it so that it doesn't anymore, it's a common practice to have typescript as a dev dependency for this reason

also ~~updates package-lock.json as it was _really_ outdated~~ deletes the old `package-lock.json`

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
@jpbberry checking previous commits it looks like `package-lock.json` is gitignored, yet it still remained in the repo. should i delete the file instead of updating it?

**Comment by jpbberry** [comment]
You can delete it. Just FYI, going through a top-gg node-sdk update right now, so I'm going to wait for that before updating this and merging your PR. May take a couple days. Thank you for the PR though!

**Comment by SuperchupuDev** [comment]
i see you released the new @topgg/sdk version some days ago, do i bump it in this PR? if so are there any breaking changes? or are you gonna do it in a separate commit

**Comment by SuperchupuDev** [comment]
@jpbberry i've gone ahead and updated to the latest @top-gg/sdk myself, since it's a patch release i hope it doesn't break anything, also removed express from the devDependencies as it wasn't used anywhere

**Comment by SuperchupuDev** [comment]
@jpbberry hey, it's been a little over 3 month since this PR was made, would you mind taking a look at it? 👀

**Comment by SuperchupuDev** [comment]
@jpbberry hey, is this planned to get merged anytime soon? i've been relying on my own fork lately that contains this fix and exactly this fix

**Comment by jpbberry** [comment]
Can you bump again and then I'll get this merged and released today

**Comment by SuperchupuDev** [comment]
thanks for replying, do you mean bumping the package.json version or pinging you?

**Comment by jpbberry** [comment]
The package.json, top-gg/sdk had another update, might as well keep up

**Comment by SuperchupuDev** [comment]
done, let me know if you need anything else 🙏

**Pull request merged**
